[package]
name = "snowy"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
crossterm = "0.27.0"
figlet-rs = "0.1.5"
inquire = "0.7.5"
regex = "1.10.4"
